name: build, deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  deployments: write

concurrency:
  group: cloudflare-pages-production
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build site
        uses: xu-cheng/texlive-action@v3
        with:
          texlive_version: 2026
          os: debian
          scheme: full
          run: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get update
            apt-get install -y --no-install-recommends \
              poppler-utils \
              perl

            ./build.sh

      - name: Deploy to CF Pages
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy public --project-name=portfolio-site
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}